Feature improvements for running at scale
LLNL/lbann pull request #1633
Opened 2020-09-18 23:12 UTC by bvanessen

2020-09-19 05:29 UTC, timmoon10 requested changes
When we actually want to merge this into develop, make sure to revert LTFB to use the validation set.

2020-09-19 05:29 UTC, timmoon10 commented on src/callbacks/ltfb.cpp
> +  m.mark_data_store_explicitly_loading(execution_mode::testing); /// @todo REMOVE
```suggestion
  m.mark_data_store_explicitly_loading(execution_mode::validation);
```

2020-09-19 05:29 UTC, timmoon10 commented on src/callbacks/ltfb.cpp
> +  c.get_trainer().evaluate(&m, execution_mode::testing); /// @todo REMOVE
```suggestion
  c.get_trainer().evaluate(&m, execution_mode::validation);
```

2020-09-19 05:29 UTC, timmoon10 commented on src/callbacks/ltfb.cpp
> +      metric_value = met->get_mean_value(execution_mode::testing); /// @todo REMOVE
```suggestion
      metric_value = met->get_mean_value(execution_mode::validation);
```

2020-09-19 05:29 UTC, timmoon10 commented on src/callbacks/ltfb.cpp
> +  m.make_data_store_preloaded(execution_mode::testing); /// @todo REMOVE
```suggestion
  m.make_data_store_preloaded(execution_mode::validation);
```

2020-09-19 23:09 UTC, timmoon10 requested changes
Revert this hack before merging back into develop.

2020-09-19 23:09 UTC, timmoon10 commented on src/callbacks/ltfb.cpp
> +    ) {
```suggestion
      || (!std::isnan(local_score) && std::isnan(partner_score))) {
```

2020-09-19 23:21 UTC, timmoon10 requested changes

2020-09-19 23:21 UTC, timmoon10 commented on src/callbacks/ltfb.cpp
> +  if (local_score == 0) { local_score = std::nan(""); } /// @todo REMOVE!
```suggestion
  const auto local_score = evaluate(*m, m_metric_name);
```

2020-09-19 23:21 UTC, timmoon10 commented on src/callbacks/ltfb.cpp
> +  if (partner_score == 0) { partner_score = std::nan(""); } /// @todo REMOVE!
```suggestion
  const auto partner_score = evaluate(*m, m_metric_name);
```

2020-10-04 23:22 UTC, bvanessen commented
@timmoon10 This PR has been rebased onto develop to get all of the new features.

2020-10-09 23:56 UTC, timmoon10 requested changes

2020-10-09 23:56 UTC, timmoon10 commented on src/data_readers/data_reader_smiles.cpp
> +  if (opts->get_bool("ltfb") && get_role() != "test") {
Is this correct?

2020-10-09 23:56 UTC, timmoon10 commented on src/training_algorithms/sgd_training_algorithm.cpp
> +    auto key = c.get_trainer().check_and_build_execution_context(c, model, execution_mode::testing);
```suggestion
    auto key = c.get_trainer().check_and_build_execution_context(c, model, execution_mode::validation);
```

2020-10-09 23:56 UTC, timmoon10 commented on src/training_algorithms/sgd_training_algorithm.cpp
> +      evaluate(evaluation_context, model, dc, execution_mode::testing);
```suggestion
    if (model.is_execution_mode_valid(execution_mode::validation)) {
      evaluate(evaluation_context, model, dc, execution_mode::validation);
```

2020-10-09 23:56 UTC, timmoon10 commented on src/callbacks/ltfb.cpp
> +  if (std::isinf(local_score)) { local_score = std::nan(""); } /// @todo REMOVE!
It makes sense to me that inf scores are invalid, but zeros could be perfectly sensible, e.g. if we evaluate with categorical accuracy.
```suggestion
  auto local_score = evaluate(*m, m_metric_name);
  if (std::isinf(local_score)) { local_score = std::nan(""); }
```

2020-10-09 23:56 UTC, timmoon10 commented on src/callbacks/ltfb.cpp
> +  if (std::isinf(partner_score)) { partner_score = std::nan(""); } /// @todo REMOVE!
```suggestion
  auto partner_score = evaluate(*m, m_metric_name);
  if (std::isinf(partner_score)) { partner_score = std::nan(""); }
```

2020-10-15 02:11 UTC, bvanessen commented on src/data_readers/data_reader_smiles.cpp
> +  if (opts->get_bool("ltfb") && get_role() != "test") {
Yes this is for the way it does LTFB.

2020-10-15 02:14 UTC, bvanessen commented
@timmoon10 I merged your suggestions. Any other ones?

2020-10-16 05:29 UTC, timmoon10 approved these changes
LGTM

2020-10-16 19:28 UTC, merged