Abstract cuDNN from LRN implementation
LLNL/lbann pull request #1647
Opened 2020-10-01 19:05 UTC by mrwyattii

Builds off work in #1638 and #1643 to abstract the cuDNN API calls out of the LRN layer. Depends on #1642, needs to be rebased after #1642 is merged.

2020-10-14 02:11 UTC, timmoon10 requested changes
Looks good, other than the `LRNDescriptor` being passed by value.

2020-10-14 02:11 UTC, timmoon10 commented on include/lbann/utils/dnn_lib/cudnn/local_response_normalization.hpp
> +void lrn_cross_channel_forward(LRNDescriptor normDesc,
```suggestion
void lrn_cross_channel_forward(LRNDescriptor const& normDesc,
```

2020-10-14 02:11 UTC, timmoon10 commented on include/lbann/utils/dnn_lib/cudnn/local_response_normalization.hpp
> +void lrn_cross_channel_backward(LRNDescriptor normDesc,
```suggestion
void lrn_cross_channel_backward(LRNDescriptor const& normDesc,
```

2020-10-14 02:11 UTC, timmoon10 commented on include/lbann/utils/dnn_lib/cudnn/local_response_normalization.hpp
> +void lrn_cross_channel_backward(LRNDescriptor normDesc,
```suggestion
void lrn_cross_channel_backward(LRNDescriptor const& normDesc,
```

2020-10-14 02:16 UTC, timmoon10 requested changes

2020-10-14 02:16 UTC, timmoon10 commented on include/lbann/layers/regularizers/local_response_normalization.hpp
> +        local_output,
Looks like we had a bug before. It should be:
```suggestion
        one,
        m_tensors_cudnn_desc.get_activations(),
        local_output,
        m_tensors_cudnn_desc.get_prev_error_signals(),
        local_gradient_wrt_output,
        m_tensors_cudnn_desc.get_prev_activations(),
        local_input,
```
I find it interesting that AlexNet was working before with this error... I suppose there's a reason LRN went out of fashion.

2020-10-15 00:19 UTC, benson31 approved these changes
LGTM

2020-10-15 17:28 UTC, timmoon10 approved these changes
:shipit:

2020-10-15 17:31 UTC, merged