Abstract cuDNN from Pooling implementation
LLNL/lbann pull request #1648
Opened 2020-10-01 22:08 UTC by mrwyattii

Builds off work in #1638 and #1643 to abstract the cuDNN API calls out of the Pooling layer. Depends on #1642, needs to be rebased after #1642 is merged.

2020-10-14 02:19 UTC, timmoon10 requested changes
LGTM after merging the suggestions.

2020-10-14 02:19 UTC, timmoon10 commented on include/lbann/utils/dnn_lib/cudnn/pooling.hpp
> +void pooling_forward(PoolingDescriptor poolingDesc,
```suggestion
void pooling_forward(PoolingDescriptor const& poolingDesc,
```

2020-10-14 02:19 UTC, timmoon10 commented on include/lbann/utils/dnn_lib/cudnn/pooling.hpp
> +void pooling_forward(PoolingDescriptor poolingDesc,
```suggestion
void pooling_forward(PoolingDescriptor const& poolingDesc,
```

2020-10-14 02:19 UTC, timmoon10 commented on include/lbann/utils/dnn_lib/cudnn/pooling.hpp
> +void pooling_backward(PoolingDescriptor poolingDesc,
```suggestion
void pooling_backward(PoolingDescriptor const& poolingDesc,
```

2020-10-14 02:19 UTC, timmoon10 commented on include/lbann/utils/dnn_lib/cudnn/pooling.hpp
> +void pooling_backward(PoolingDescriptor poolingDesc,
```suggestion
void pooling_backward(PoolingDescriptor const& poolingDesc,
```

2020-10-15 17:31 UTC, timmoon10 approved these changes
:shipit:

2020-10-15 17:32 UTC, benson31 approved these changes
LGTM

2020-10-15 17:32 UTC, merged