Refactor CUDA unary math functions
LLNL/lbann pull request #1670
Opened 2020-10-16 23:32 UTC by mrwyattii

Refactors the declaration and definition of cuda unary math functions to avoid template specialization (and unconstrained templates) in favor or function overloading.  This addresses an issue where there is *not* a template specialization for a particular type, causing issues where the code compiles but does not link ("undefined reference to function").  

This is part 1 of 3 in porting the `gpu_lib` backend to HIP/ROCm.

2020-10-21 01:17 UTC, timmoon10 requested changes
Template specialization feels more correct than function overloads. As an alternative approach, how about we make the generic template implementation cast to `float`, call the `float` version of the function, and cast back to the original type. That way there's always a valid implementation for floating-point types and we avoid the linking errors. If our GPUs have compute capability >=5.3, then we can specialize for `__half`. I think we can put all this logic when we define `DECLARE_UNARY_MATH_FUNC_WITH_TYPE` and `DECLARE_BINARY_MATH_FUNC_WITH_TYPE`, which would allow us to remove the separate section for the `__half` specializations.

That said, in practice I don't think it's a major difference. Most cases will require their own specializations, so templating isn't at its full usefulness. @benson31 Are there considerations for meta-programming magic?

I think the only operations that need a generic template implementation are min and max, and maybe abs. This might help simplify things a little.

2020-10-23 20:30 UTC, mrwyattii commented on include/lbann/utils/gpu/cuda.hpp
>  template <typename T> __device__ __forceinline__ bool isnan(const T& x);
This isn't correct.  The template definition only serves to get those functions in the `lbann::cuda::` namespace (https://github.com/LLNL/lbann/blob/a11d7c43e51b259925d9ecf335794a851d8a3923/include/lbann/utils/impl/cuda.hpp#L179) as `isinfite`, `isinf`, and `isnan` are already overloaded functions in cuda (https://developer.download.nvidia.com/cg/isfinite.html).

If we do try to define them (e.g., `__device__ __forceinline__ bool isfinite(float const& x) { ... };`) then we run into errors:
```
error: cannot overload functions distinguished by return type alone
```

2020-10-23 20:40 UTC, mrwyattii commented on include/lbann/utils/gpu/cuda.hpp
> +DECLARE_BINARY_UNARY_MATH_FUNC(pow);
This has been corrected in 99311868cd0aa30a3ca90c7eac3e1f62e5fac18e

2020-10-26 18:32 UTC, timmoon10 approved these changes

2020-10-26 20:23 UTC, benson31 approved these changes
LGTM

2020-10-27 00:13 UTC, merged