Implementation of perturb learning rate callback
LLNL/lbann pull request #1823
Opened 2021-03-11 01:09 UTC by samadejacobs

Callback for learning rate exploration in tournament (population)-based training. Current implementation supports 
random perturbation, performed in log space.

2021-03-15 15:57 UTC, timmoon10 requested changes
Two requests:
- Change name to "perturb_learning_rate". The meaning of LR is not obvious to me.
- Make sure we don't perturb at every step (I now see why my experiments with perturbing Adam were so volatile...).

2021-03-15 15:57 UTC, timmoon10 commented on src/callbacks/perturb_lr.cpp
> +  if (m_perturb_during_training && c.get_step() > 0) {
We should only perturb once per interval:
```suggestion
  if (m_perturb_during_training
      && c.get_step() % m_batch_interval == 0
      && c.get_step() > 0) {
```

2021-03-23 00:48 UTC, samadejacobs commented
Two requests by @timmoon10 addressed in latest push.

2021-03-23 15:25 UTC, timmoon10 approved these changes
LGTM. If there aren't any new failures in Bamboo, we can merge.

2021-03-23 17:17 UTC, merged