Subgraph Parallelism support for Transformer models
LLNL/lbann pull request #1879
Opened 2021-06-02 05:19 UTC by aj-prime

This PR exposes subgraph parallelism as a new strategy to parallelize the DNN training by processing different branches on separate GPUs.

It implements Data Sub-Graph Parallelism (D&SP) and D&SP-cSub designs. 

Initial support is available to extend sub-graph parallelism for common layers in Transformer models to train out-of-core transformer models. 

An example is available in "applications/nlp/transformer/subgraph" directory. 

Note: It does not support multiple trainers and needs "translatebetweengrid" functions in Hydrogen.

2021-06-10 09:01 UTC, timmoon10 commented on include/lbann/layers/transform/dist_SOB.hpp
> +  extern template class dist_SOB_layer<T, data_layout::MODEL_PARALLEL, Device>
Model-parallel case is not supported.
```suggestion
  extern template class dist_SOB_layer<T, data_layout::DATA_PARALLEL, Device>;
```

2021-06-12 00:53 UTC, timmoon10 requested changes
I've raised a few correctness issues that should be addressed before merging. It looks like handles the use-cases from the paper well, although it's all very kludgy. It's not __too__ terrible as long as this is an expert feature, although we should clean things up at some point in the future.

2021-06-12 00:53 UTC, timmoon10 commented on src/models/model.cpp
> +      counter++;
`counter` doesn't do anything:
```suggestion
  for (auto rit = m_weights.rbegin(); rit != m_weights.rend(); ++rit) {
    auto& w = **rit;
    auto&& opt = w.get_optimizer();
    if (opt != nullptr) {
      do_weight_optimize_begin_cbs(&w);
      opt->step();
      do_weight_optimize_end_cbs(&w);
```

2021-06-16 20:19 UTC, aj-prime commented on include/lbann/layers/layer.hpp
> +  int enable_vector_copy = 0;
This variable can have multiple values. Ranging from 0 to 2.

2021-06-29 16:59 UTC, timmoon10 approved these changes
Pending no new Bamboo failures, this is ready to merge.

2021-07-01 23:36 UTC, timmoon10 commented
@mrwyattii Do we see any build errors on Corona?

2021-07-06 21:10 UTC, timmoon10 commented
[No new Bamboo errors](https://lc.llnl.gov/bamboo/browse/LBANN-TIM377-8).

2021-07-07 05:15 UTC, merged