Add functionality to insert, remove and replace layers in the model
LLNL/lbann pull request #1899
Opened 2021-06-28 23:00 UTC by soumyadipghosh

- Adds insert, remove and replace functions to modify layers in the model
- Adds corresponding unit tests

NOTE: There is an assumption that the layer being modified has just one parent and one child.

2021-06-28 23:13 UTC, timmoon10 commented
[Bamboo is running](https://lc.llnl.gov/bamboo/browse/LBANN-TIM378-1).

2021-06-30 20:14 UTC, samadejacobs approved these changes
LGTM

2021-07-02 04:55 UTC, timmoon10 requested changes
Mostly looks good. Just an edge case if a parent layer has multiple children.

2021-07-02 04:55 UTC, timmoon10 commented on src/models/model.cpp
> +  parent.add_child_layer(l.get_child_layer_pointer(0));
We should handle the case where `parent` has multiple children:
```suggestion
  parent.replace_child_layer(l.get_child_layer_pointer(0), parent.find_child_layer_index(l));
```

2021-07-02 04:55 UTC, timmoon10 commented on src/models/model.cpp
> +  parent.add_child_layer(new_layer);
We should handle the case where `parent` has multiple children:
```suggestion
  parent.replace_child_layer(new_layer, parent.find_child_layer_index(l));
```

2021-07-06 22:31 UTC, benson31 approved these changes
Once @timmoon10 is happy, I'm ok with the rest of this.

2021-07-06 22:40 UTC, timmoon10 approved these changes

2021-07-06 22:40 UTC, merged