Channelwise Fully Connected Distconv Layer
LLNL/lbann pull request #1901
Opened 2021-06-29 22:46 UTC by szaman19

- Adds distributed tensor implementation of channel-wise fully connected layer  
- Distributes input tensor in the channel dimension for a 4D input tensor of the form (Batch_size, channels, *, *)

2021-07-09 01:24 UTC, timmoon10 requested changes

2021-07-09 01:24 UTC, timmoon10 commented on include/lbann/layers/learning/distconv/distconv_layers.hpp
> +    output_local_shape[0] = linearity_dims[0];
I don't think we are handling the transpose case.

2021-07-09 01:24 UTC, timmoon10 commented on src/layers/learning/channelwise_fully_connected.cpp
> +
If we are just calling the base class implementation, do we need to override these functions?
```suggestion
```

2021-07-09 01:24 UTC, timmoon10 commented on src/layers/learning/channelwise_fully_connected.cpp
> +    1, std::multiplies<size_t>());
```suggestion
  const auto& output_channel_size = std::accumulate(
    output_channel_dims.begin(), output_channel_dims.end(),
    1, std::multiplies<size_t>());
```

2021-07-09 01:24 UTC, timmoon10 commented on src/layers/learning/channelwise_fully_connected.cpp
> +  }
```suggestion
  if(this->distconv_enabled()){
    this->get_distconv_adapter().fp_compute();
    return ;
  }
```

2021-07-09 01:24 UTC, timmoon10 commented on src/layers/learning/channelwise_fully_connected.cpp
> +  }
```suggestion
  if(this->distconv_enabled()){
    this->get_distconv_adapter().bp_compute();
    return ;
  }
```

2021-07-09 02:06 UTC, szaman19 commented on src/layers/learning/channelwise_fully_connected.cpp
> +  std::vector<int> linearity_dims{1, 1, input_channel_size, output_channel_size};
We support it, but the linearity get's reshaped here: 

https://github.com/LLNL/lbann/blob/f5ec5481db47f1ef37208deceb56904ed32d6250/src/layers/learning/distconv/distconv_layers.cpp#L57

I think it makes sense to move that change dimensionality switch from the distconv side and put it in the `channelwise_fully_connected.cpp`.

2021-07-10 16:24 UTC, timmoon10 requested changes
One correctness bug and some style suggestions, but otherwise LGTM.

2021-07-10 16:24 UTC, timmoon10 commented on src/layers/learning/distconv/distconv_layers.cpp
> +    }
```suggestion
    if(output.get_buffer() == nullptr){
      util::MPIRootPrintStreamInfo()<< "output buffer is null";
    }

    if(input.get_buffer() == nullptr){
      util::MPIRootPrintStreamInfo() << "input buffer is null";
    }

    if(linearity.get_buffer() == nullptr){
      util::MPIRootPrintStreamInfo() <<"linearity buffer is null";
    }
```

2021-07-10 16:24 UTC, timmoon10 commented on src/layers/learning/distconv/distconv_layers.cpp
> +    }
This matrix doesn't seem to be used:
```suggestion
```

2021-07-10 16:24 UTC, timmoon10 commented on src/layers/learning/distconv/distconv_layers.cpp
> +    El::Matrix<DataType, El::Device::GPU>  output_grad_mat_reshaped;
These don't seem to be used:
```suggestion
```

2021-07-10 16:24 UTC, timmoon10 commented on bamboo/unit_tests/test_unit_layer_channelwise_fully_connected_distconv.py
> +    num_height_groups = tools.gpus_per_node(lbann)
Let's make this name more accurate:
```suggestion
    num_channel_groups = tools.gpus_per_node(lbann)
```

2021-07-10 16:24 UTC, timmoon10 commented on bamboo/unit_tests/test_unit_layer_channelwise_fully_connected_distconv.py
> +    # Data-parallel distconv layout, non-transpose, bias
```suggestion
    # Non-transpose, bias
```

2021-07-10 16:24 UTC, timmoon10 commented on bamboo/unit_tests/test_unit_layer_channelwise_fully_connected_distconv.py
> +    metrics.append(lbann.Metric(z, name='data-parallel layout, non-transpose, bias'))
```suggestion
    metrics.append(lbann.Metric(z, name='non-transpose, bias'))
```

2021-07-10 16:24 UTC, timmoon10 commented on bamboo/unit_tests/test_unit_layer_channelwise_fully_connected_distconv.py
> +    # Data-parallel distconv layout, non-transpose, no bias
```suggestion
    # Non-transpose, no bias
```

2021-07-10 16:24 UTC, timmoon10 commented on bamboo/unit_tests/test_unit_layer_channelwise_fully_connected_distconv.py
> +    metrics.append(lbann.Metric(z, name='data-parallel layout, non-transpose, no bias'))
```suggestion
    metrics.append(lbann.Metric(z, name='non-transpose, no bias'))
```

2021-07-10 16:24 UTC, timmoon10 commented on bamboo/unit_tests/test_unit_layer_channelwise_fully_connected_distconv.py
> +    # Data-parallel layout, transpose, bias
```suggestion
    # Transpose, bias
```

2021-07-10 16:24 UTC, timmoon10 commented on bamboo/unit_tests/test_unit_layer_channelwise_fully_connected_distconv.py
> +    metrics.append(lbann.Metric(z, name='data-parallel layout, transpose, bias'))
```suggestion
    metrics.append(lbann.Metric(z, name='transpose, bias'))
```

2021-07-10 16:24 UTC, timmoon10 commented on bamboo/unit_tests/test_unit_layer_channelwise_fully_connected_distconv.py
> +    # Data-parallel layout, transpose, no bias
```suggestion
    # Transpose, no bias
```

2021-07-10 16:24 UTC, timmoon10 commented on bamboo/unit_tests/test_unit_layer_channelwise_fully_connected_distconv.py
> +    metrics.append(lbann.Metric(z, name='data-parallel layout, non-transpose, no bias'))
```suggestion
    metrics.append(lbann.Metric(z, name='Non-transpose, no bias'))
```

2021-07-12 17:46 UTC, timmoon10 approved these changes

2021-07-12 20:49 UTC, merged