Add axis paramter to Scatter-Gather layers
LLNL/lbann pull request #1928
Opened 2021-07-22 20:16 UTC by szaman19

- Allows us to specify the dimension to scatter or gather along given 2D inputs

2021-07-23 00:29 UTC, timmoon10 requested changes
I see some correctness issues, so I wonder why the Bamboo test didn't catch them. Before fixing the other bugs, we should rework the tests until we get failures.

We also need to update the serialization functions in `src/layers/transform/cereal_registration/{gather,scatter}.cpp` to serialize the gather/scatter axis.

2021-07-23 00:29 UTC, timmoon10 commented on src/layers/transform/gather.cu
> +      Dim3{static_cast<size_t>(local_output.LDim()), value_stride_2, 1});
```suggestion
      Dim3{static_cast<size_t>(local_output.LDim()), output_stride_2, 1});
```

2021-07-23 00:29 UTC, timmoon10 commented on src/layers/transform/gather.cu
> +        Dim3{static_cast<size_t>(local_output_grad.LDim()),value_stride_2, 1},
```suggestion
        Dim3{local_mini_batch_size, num_output_rows, output_size},
        Dim3{static_cast<size_t>(local_output_grad.LDim()),output_stride_2, 1},
```

2021-07-23 00:29 UTC, timmoon10 commented on src/layers/transform/gather.cu
> +        Dim3{local_mini_batch_size, num_rows, output_size},
```suggestion
        Dim3{local_mini_batch_size, num_output_rows, output_size},
```

2021-07-23 00:29 UTC, timmoon10 commented on src/layers/transform/scatter.cu
> +        Dim3{static_cast<size_t>(local_output.LDim()), value_stride_2, 1});
```suggestion
        Dim3{local_mini_batch_size, num_output_rows, output_size},
        Dim3{static_cast<size_t>(local_output.LDim()), output_stride_2, 1});
```

2021-07-23 00:29 UTC, timmoon10 commented on src/layers/transform/scatter.cu
> +        Dim3{static_cast<size_t>(local_output_grad.LDim()), value_stride_2, 1},
```suggestion
        Dim3{local_mini_batch_size, num_output_rows, output_size},
        Dim3{static_cast<size_t>(local_output_grad.LDim()), output_stride_2, 1},
```

2021-07-23 00:29 UTC, timmoon10 commented on src/layers/transform/scatter.cu
> +        Dim3{local_mini_batch_size, num_rows, output_size},
```suggestion
        Dim3{local_mini_batch_size, num_output_rows, output_size},
```

2021-07-23 00:29 UTC, timmoon10 commented on bamboo/unit_tests/test_unit_layer_gather.py
> +num_rows = 10
It's worrying that this test didn't catch some correctness bugs. Maybe the tensor dimensions were too nice.
```suggestion
num_rows = 11
```

2021-07-23 00:29 UTC, timmoon10 commented on bamboo/unit_tests/test_unit_layer_scatter.py
> +output_size = 7
```suggestion
width = 13
height = 7
input_size = width * height 
output_size = 23
```

2021-07-23 00:29 UTC, timmoon10 commented on bamboo/unit_tests/test_unit_layer_scatter.py
> +    metrics.append(lbann.Metric(z, name='obj_2'))
```suggestion
    metrics.append(lbann.Metric(z, name='2D, axis=0'))
```

2021-07-23 00:29 UTC, timmoon10 commented on bamboo/unit_tests/test_unit_layer_scatter.py
> +    metrics.append(lbann.Metric(z, name='obj_3'))
```suggestion
    metrics.append(lbann.Metric(z, name='2D, axis=1'))
```

2021-07-23 02:35 UTC, szaman19 commented on src/layers/transform/gather.cu
> +template <typename T, bool has_row_vectors>
So, I wasn't sure if there would be issues with having the branch inside the kernel performance-wise. The `has_row_vectors` check would happen for every element in the input (unless optimized away of course).

2021-07-23 02:41 UTC, szaman19 commented on src/layers/transform/scatter_builder.cpp
> +  auto axis = proto_layer.scatter().axis().value();
I wasn't sure. I would prefer no default and make it a requirement, but that doesn't make sense for the 1D case.

2021-07-23 03:09 UTC, szaman19 commented on src/layers/transform/gather.cpp
> +  const El::Int bounds = is_axis_0? this->get_output_dims()[0]: values_size;
Yup, that's obviously wrong. I wonder why this passed bamboo...

2021-07-27 22:53 UTC, timmoon10 commented on src/layers/transform/gather.cu
> +template <typename T, bool has_row_vectors>
There may be some performance impact, but I don't expect it to be huge since all the threads would follow the same branch path.

2021-07-27 23:03 UTC, timmoon10 approved these changes
Overall looks good. [Bamboo is running](https://lc.llnl.gov/bamboo/browse/LBANN-TIM391-1).

I notice that the default value of `axis=-1` causes a failure in the 2D case. It's not a bad idea since it encourages being explicit. That said, following NumPy/PyTorch notation, I would expect the `-1` axis to correspond to the last tensor dim (axis 1 for 2D tensors).

2021-07-28 15:55 UTC, szaman19 commented
> I notice that the default value of `axis=-1` causes a failure in the 2D case. It's not a bad idea since it encourages being explicit. That said, following NumPy/PyTorch notation, I would expect the `-1` axis to correspond to the last tensor dim (axis 1 for 2D tensors).

Yeah, since the axis argument significantly changes the dimensions of the output, it made sense to be more explicit rather than setting a default. The behavior should be revisited once we support higher dimension tensors, I think (along with the kernels).

2021-07-28 20:48 UTC, merged