LTFB with Truncation Selection Exchange
LLNL/lbann pull request #1945
Opened 2021-08-09 16:40 UTC by samadejacobs

This PR implements LTFB training algorithm with truncation selection exchange (TSE). Unlike classic LTFB with random pairwise exchange (RPE), trainers in TSE are ranked first using specified (tournament) evaluation metric. Trainers with low scores using a threshold (determined by user specified _truncation_k_) receives model parameters, training hyperparameters and or topologies from a trainer with high score. 

Unit/integration test will added to this PR or go in a separate follow up PR.

2021-08-11 20:37 UTC, benson31 approved these changes
Other than a few minor issues and code clutter and LOTS of superfluous vertical whitespace, this seems fine.

2021-08-11 20:37 UTC, benson31 commented on src/execution_algorithms/ltfb/checkpoint_common.hpp
> +
If this is all dead code, just remove it?
```suggestion
```

2021-08-11 20:37 UTC, benson31 commented on src/execution_algorithms/ltfb/truncation_selection_exchange.cpp
> +    LBANN_ERROR(err.str());
```suggestion
    LBANN_ERROR("could not find metric \"", metric_name, "\" "
                "in model \"", m.get_name(), "\"");
```
Just use the macro. It builds the string for you.

2021-08-11 20:37 UTC, benson31 commented on src/execution_algorithms/ltfb/truncation_selection_exchange.cpp
> +                                         data_coordinator& dc) const
```suggestion
void TruncationSelectionExchange::select_next(model& m,
                                              ltfb::ExecutionContext& ctxt,
                                              data_coordinator& dc) const
```
Or just run `clang-format`.

2021-08-11 20:37 UTC, benson31 commented on include/lbann/execution_algorithms/ltfb/truncation_selection_exchange.hpp
> +                         int truncation_k);
```suggestion
  TruncationSelectionExchange(std::string metric_name,
                              metric_strategy winner_strategy,
                              int truncation_k);
```
Or just run `clang-format`.

2021-08-11 20:37 UTC, benson31 commented on src/execution_algorithms/ltfb/truncation_selection_exchange.cpp
> +{}
```suggestion
TruncationSelectionExchange::TruncationSelectionExchange(
  std::string metric_name,
  metric_strategy winner_strategy,
  int truncation_k)
  : TruncationSelectionExchange({{std::move(metric_name), winner_strategy}}, truncation_k)
{}
```

2021-08-11 20:37 UTC, benson31 commented on src/execution_algorithms/ltfb/truncation_selection_exchange.cpp
> +                                       data_coordinator& dc) const
```suggestion
EvalType TruncationSelectionExchange::evaluate_model(model& m,
                                                     ExecutionContext& ctxt,
                                                     data_coordinator& dc) const
```
Or just run `clang-format`.

2021-08-11 20:37 UTC, benson31 commented on src/execution_algorithms/ltfb/truncation_selection_exchange.cpp
> +            /*force=*/true);
```suggestion
      m.setup(trainer.get_max_mini_batch_size(),
              metadata,
              /*force=*/true);
```
Or just run `clang-format`.

2021-08-11 22:11 UTC, bvanessen requested changes
Please add some sort of test.

2021-08-11 22:11 UTC, bvanessen commented on python/lbann/core/training_algorithm.py
> +class KFAC(TrainingAlgorithm):
Is this duplicate code, or a weird artifact of the commit?

2021-08-11 22:11 UTC, bvanessen commented on include/lbann/execution_algorithms/ltfb/truncation_selection_exchange.hpp
> +class TruncationSelectionExchange final
@samadejacobs Please add some unit tests to the PR so that we can ensure that this algorithm continues to work into the future.  Additionally, please update the release notes to keep track of the new features that are being added.  Also, can we get some documentation for the new code.

2021-08-12 16:41 UTC, benson31 commented on src/execution_algorithms/ltfb/truncation_selection_exchange.cpp
> +    LBANN_ERROR(err.str());
```suggestion
    LBANN_ERROR("truncation tournament exchange currently works "
                "if trainers scores are unique")
```

2021-08-18 22:38 UTC, bvanessen approved these changes

2021-08-18 22:38 UTC, merged