Bugfix for the checkpoint lenet unit tests
LLNL/lbann pull request #2035
Opened 2022-01-25 21:13 UTC by bvanessen

Updated the checkpoint logic so that when checkpointing during a
validation phase it will use the current epoch and step counts of the
active trainng execution context.  This will allow the validation
checkpoints to be properly ordered between the normal training
checkponts.  Additionally, under the new SGD execution algorithm, the
validation execution context is reset for every validation phase.  As
a result, two helper functions were added to the checkpoint class that
allow the callback to find the current active training execution
context if it was available, otherwise the active execution context is
used.  This ensures that in an inference only run with checkpoint, the
normal behavior should be preserved.

2022-01-25 21:19 UTC, bvanessen commented
CI is running here https://lc.llnl.gov/gitlab/vanessen/lbann/-/pipelines/140297

2022-01-25 21:50 UTC, benson31 approved these changes
Overall seems fine. If CI's happy, I'm happy.

2022-01-25 21:50 UTC, benson31 commented on include/lbann/callbacks/checkpoint.hpp
> +  }
```suggestion
  inline const SGDExecutionContext& get_current_execution_context_with_training_override(model* m) const {
    const auto& c = dynamic_cast<SGDExecutionContext&>(m->get_execution_context());
    if(c.get_execution_mode() != execution_mode::training &&
       this->get_active_trainer().execution_context_valid(m, execution_mode::training)) {
      return dynamic_cast<SGDExecutionContext&>(
        this->get_active_trainer().get_execution_context(m, execution_mode::training));
    }
    return c;
  }
```

2022-01-25 21:50 UTC, benson31 commented on include/lbann/callbacks/checkpoint.hpp
> +  inline size_t get_epoch_with_training_override(model* m) {
```suggestion
  inline size_t get_epoch_with_training_override(model* m) const {
```

2022-01-25 21:50 UTC, benson31 commented on include/lbann/callbacks/checkpoint.hpp
> +  inline size_t get_step_with_training_override(model* m) {
```suggestion
  inline size_t get_step_with_training_override(model* m) const {
```

2022-01-25 21:51 UTC, benson31 commented
Actually, these three functions should probably be `private:` too. But so should most of this interface and it isn't so we can clean it all up later (and hopefully promote checkpointing to a first-class feature and thus get rid of the callback).

2022-01-25 21:53 UTC, benson31 commented on src/trainers/trainer.cpp
> +  return execution_context_valid(key);
```suggestion
  return execution_context_valid(std::make_pair(model, mode));
```
Avoid the copy.

2022-01-25 22:14 UTC, benson31 requested changes
Upon further reflection, I think I feel strongly that the definitions added to `checkpoint.hpp` should be moved to the `.cpp`. I'm not _thrilled_ that the name `SGDExecutionContext` is being added to this header file, but that can be hidden with a forward declaration rather than an `#include` as long as it's just used by reference.

It would be better if these functions were written as free functions instead and put in an anonymous namespace in `checkpoint.cpp`.

2022-01-26 02:00 UTC, benson31 approved these changes
lGTM

2022-01-26 06:19 UTC, merged