Document layers
LLNL/lbann pull request #2067
Opened 2022-02-16 22:49 UTC by graham63

2022-02-22 07:50 UTC, timmoon10 approved these changes
I think this is a good layout. It looks nice and I like the tables summarizing the layers in each page.

Comments:
- I'm not a fan of how we handle the one-line descriptions:
  ```
  The <name> layer is <brief description>. <detailed description>.
  ```
  It feels redundant and [Google doesn't like it](https://developers.google.com/style/api-reference-comments). Could we change it to something like:
  ```
  <brief description>
  
  <detailed description>
  ```
- When a layer has no additional arguments, I think putting `Arguments: None` is redundant.
- I notice the argument types are Protobuf types, not Python. Most of the conversions are obvious, but some of them are a bit idiosyncratic (e.g. using `google.protobuf.BoolValue` as a hack to have non-false default values for `bool`).

After fixing the typos, I think this is good to merge. I can take a followup pass to deal with the Protobuf/Python type issue.

2022-02-22 07:50 UTC, timmoon10 commented on docs/layers/transform_layers.rst
> +The Bernoulli layer is a random tensor with a Bernoulli distribution
```suggestion
The Bernoulli layer is a random tensor with a Bernoulli distribution.
```

2022-02-22 07:50 UTC, timmoon10 commented on docs/layers/transform_layers.rst
> +The InTopK layer is a one-hot vector indicating top-k entries Output
```suggestion
The InTopK layer is a one-hot vector indicating top-k entries. Output
```

2022-02-22 07:50 UTC, timmoon10 commented on docs/layers/transform_layers.rst
> +The Slice layer slices a tensor along a specified dimension The tensor
```suggestion
The Slice layer slices a tensor along a specified dimension. The tensor
```

2022-02-22 07:50 UTC, timmoon10 commented on docs/layers/learning_layers.rst
> +The ChannelwiseFullyConnected layer appliesan  affine transformation
```suggestion
The ChannelwiseFullyConnected layer applies an affine transformation
```

2022-02-22 07:50 UTC, timmoon10 commented on docs/layers/learning_layers.rst
> +:math:`\text{num\_channels} \times 2` matrix, where the first column
```suggestion
:math:`\text{num_channels} \times 2` matrix, where the first column
```

2022-02-22 07:50 UTC, timmoon10 commented on docs/layers/learning_layers.rst
> +Deconvolution Layer. Reverses the effects of convolution.
```suggestion
Deconvolution Layer. Transpose of convolution.
```
Once https://github.com/LLNL/lbann/pull/1997 is merged, the text should be ported here.

2022-02-22 07:50 UTC, timmoon10 commented on docs/layers/learning_layers.rst
> +(:math:`3 \text{hidden\_size}`).
```suggestion
Expects two inputs: a 2D input sequence (
:math:`\text{sequence_length}\times\text{input_size}`) and a 2D
initial hidden state (
:math:`\text{num_layers}\times\text{hidden_size}`).

Uses four weights per GRU cell: "ih\_matrix" (
:math:`3 \text{hidden_size}\times\text{input_size}` for layer 0 and
:math:`3 \text{hidden_size}\times\text{hidden_size}` for other layers),
"hh\_matrix" (:math:`3 \text{hidden_size}\times\text{hidden_size}`),
"ih_bias" (:math:`3 \text{hidden_size}`), "hh_bias"
(:math:`3 \text{hidden_size}`).
```

2022-02-22 07:50 UTC, timmoon10 commented on docs/layers/learning_layers.rst
> +.. todo:: Support bidirectional RNNs
This is putting everything inside of the todo block. Maybe:
```suggestion
    .. todo:: Support bidirectional RNNs
    
Arguments:
```

2022-02-22 07:50 UTC, timmoon10 commented on docs/layers/math_layers.rst
> +Absolute value of discrete Fourier transform One-, two-, or
```suggestion
Absolute value of discrete Fourier transform. One-, two-, or
```

2022-02-22 07:50 UTC, timmoon10 commented on docs/layers/regularization_layers.rst
> +The values multiplied by 1/(keep probability) at training time. Keep
```suggestion
The values are multiplied by 1/(keep probability) at training time. Keep
```

2022-02-22 17:45 UTC, bvanessen approved these changes
LGTM.  I reviewed and applied @timmoon10 suggestions.

2022-02-23 17:30 UTC, benson31 requested changes
Generally looks good. Just fix the dangling references and :shipit:

2022-02-23 17:30 UTC, benson31 commented on docs/layers.rst
> +:ref:`layers-list`. See :ref:`layer-options` for layer parameter option.
These are both dangling references.

2022-02-24 21:13 UTC, benson31 approved these changes
LGTM

2022-02-24 21:13 UTC, merged