Move python docstrings to rst files
LLNL/lbann pull request #2071
Opened 2022-03-02 19:26 UTC by graham63

2022-05-18 14:18 UTC, benson31 requested changes
Generally seems good. There are just a few issues that should be easy to resolve.

2022-05-18 14:18 UTC, benson31 commented on docs/execution_algorithms/ltfb.rst
> +                          list of kwargs.
Can the path here be hyperlinked to the GitHub link for that file?

2022-05-18 14:18 UTC, benson31 commented on docs/execution_algorithms/ltfb.rst
> +.. py:class:: KFAC(TrainingAlgorithm)
This class should get its own page; it's distinct from LTFB.

2022-05-18 14:18 UTC, benson31 commented on docs/execution_algorithms/ltfb.rst
> +lbann.LTFB module
I don't think "module" is the right word here, as that's meaningful in Python contexts, and that's not how we mean it here. Maybe just "interface"?

2022-05-18 14:18 UTC, benson31 commented on docs/execution_algorithms/batched_iterative_optimization.rst
> +lbann.BatchedIterativeOptimizer module
See comment in LTFB file. Maybe "interface" instead of "module"?

2022-05-18 14:18 UTC, benson31 commented on docs/execution_algorithms.rst
> +lbann.TrainingAlgorithm module
See comment in LTFB file. Maybe "interface" instead of "module"?

2022-05-18 14:18 UTC, benson31 commented on docs/execution_algorithms/batched_iterative_optimization.rst
> +         :param float seconds: Number of epochs.
```suggestion
         :param float seconds: Time limit in seconds.
```

2023-01-26 01:05 UTC, benson31 commented on docs/execution_algorithms.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lbann.TrainingAlgorithm interface
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-01-26 01:06 UTC, bvanessen approved these changes

2023-01-26 01:06 UTC, benson31 approved these changes

2023-01-26 01:06 UTC, merged