Update U-Net model
LLNL/lbann pull request #2151
Opened 2022-11-07 07:53 UTC by bvanessen

Updated the HDF5 legacy data reader and U-Net model to use the new
input layer API.  Added a routine to fetch data fields for label reconstruction.

2022-11-07 19:14 UTC, bvanessen commented
It is currently failing on pascal with `CUDNN_LOGINFO_DBG=1 CUDNN_LOGWARN_DBG=1 CUDNN_LOGERR_DBG=1 CUDNN_LOGDEST_DBG=cudnn_log_%i.txt python3 unet3d.py --nodes 1 --procs-per-node 2 --partition-level 2 --depth-groups 2`

2022-11-28 17:51 UTC, bvanessen commented
@fiedorowicz1 This PR now has partial support for multiple samples per rank in the Cosmoflow application.

2022-12-05 19:29 UTC, fiedorowicz1 commented on applications/physics/cosmology/cosmoflow/cosmoflow_network_architectures.py
> +
This file needs a numpy import: `import numpy as np`

2023-01-10 16:24 UTC, benson31 commented on include/lbann/utils/exception.hpp
> +  int dummy[] = { (oss << std::setfill('0') << std::setw(7) << args, 0)... };
```suggestion
  int dummy[] = { (oss << args, 0)... };
```

2023-01-30 19:59 UTC, benson31 requested changes
Seems reasonable, but let's discuss and address the excess of print statements this adds.

2023-01-30 19:59 UTC, benson31 commented on include/lbann/data_readers/data_reader_hdf5_legacy.hpp
> +                   int data_id);
```suggestion
  void load_sample(conduit::Node& node, int data_id);
```

2023-01-30 19:59 UTC, benson31 commented on include/lbann/layers/layer.hpp
>  }
```suggestion
static std::ostream &print_parallel_strategy_header(std::ostream &os) {
  os << "Axis over which DistConv can parallelize:\n"
     << "\tSamples in the mini-batch (N)\n"
     << "\tDepth, Height, and Width (D x H x W)\n"
     << "\tChannel (C)\n"
     << "\tFilters (F)\n"
     << "\tReplications (R): Number of times the layer is replicated (for FC layers right now)\n"
     << "\tBranch number in the subgraph (T)\n"
     << "\tPercentage of parent resources to be allocated to this branch (%)\n"
     << "\tEnable subgraph for the layer (e)\n"
     << "\nFor each of the above dimensions there are two fields:\n"
     <<"\t# Groups (G): refers to how many reduced-order tensors exist with respect to that dimension" << std::endl
     << "\t             e.g. For a kD tensor you would have a stack of G (k-1)D tensors" << std::endl
     << "\t\t[N, C, D, H, W]" << std::endl
     << "\t\t[2, 1, 4, 1, 1] ---" << std::endl
     << "\t\t                  |" << std::endl
     << "\t\t                  V" << std::endl
     << "\t\t  4 Depth groups: [N, C, H, W]" << std::endl
     << "\t\t                  [2, 1, 1, 1]" << std::endl
     << "\t\t                  [2, 1, 1, 1]" << std::endl
     << "\t\t                  [2, 1, 1, 1]" << std::endl
     << "\t\t                  [2, 1, 1, 1]" << std::endl
     << "\t\t[1, 1, 4, 1, 2] ---" << std::endl
     << "\t\t                  |" << std::endl
     << "\t\t                  V" << std::endl
     << "\t\t 2 Sample groups: [C, D, H, W]" << std::endl
     << "\t\t                  [1, 4, 1, 1]" << std::endl
     << "\t\t                  [1, 4, 1, 1]" << std::endl
     << "\n\tSplit per Dimension (S): Number of groups the dimension is split over (i.e. split K times) (aka H2 split shape) (must divide groups evenly).\n"
     << std::endl;


  os << "Reporting order for the parallel strategy" << std::endl;
  os << "{"  << "N: " << "G" << "/" << "S"
     << ", " << "C: " << "G" << "/" << "S"
     << ", " << "D: " << "G" << "/" << "S"
     << ", " << "H: " << "G" << "/" << "S"
     << ", " << "W: " << "G" << "/" << "S"
     << ", " << "F: " << "G" << "/" << "S"
     << ", " << "R:"
     << ", " << "T:"
     << ", " << "%:"
     << ", " << "e:"
     << "}";
  return os;
}
```
I'm not sure we actually want to print this. It takes a lot of terminal/log file real estate for something that, frankly, is neither interesting nor compilcated.

If we decide to proceed anyway with this, I'd recommend cleaning it up (get rid of the extraneous `<<` tokens and `std::endl`s) and perhaps only printing it in debug builds.

2023-01-30 19:59 UTC, benson31 commented on python/lbann/contrib/args.py
> +#        'LBANN_DISTCONV_TENSOR_SHUFFLER': 'HYBRID',
```suggestion
        'LBANN_DISTCONV_HALO_EXCHANGE': 'AL',
        'LBANN_DISTCONV_TENSOR_SHUFFLER': 'AL',
```

2023-01-30 19:59 UTC, benson31 commented on src/models/model.cpp
> +    std::cout << "\nParallel Strategy description - " << ss.str() << std::endl;
```suggestion
    std::cout << "\nDistconv-enabled layers:\n\t" << dc_enabled.str() << "\n\n"
              << "Distconv-disabled layers:\n\t" << dc_disabled.str() << "\n\n"
              << "Parallel Strategy description - ";
    print_parallel_strategy_header(std::cout);
    endl(std::cout);
```

2023-01-31 17:20 UTC, benson31 approved these changes

2023-01-31 17:21 UTC, merged