Add contributor guidelines and pre-commit hooks
LLNL/lbann pull request #2197
Opened 2023-02-17 21:23 UTC by tbennun

2023-02-18 01:07 UTC, bvanessen requested changes
Need to finish the clang format first, but generally looks good.

2023-03-16 16:39 UTC, tbennun commented
@benson31 @bvanessen with the new formatting merged, this is now ready for (re-)review.

I ran it on different systems and, since `pre-commit` hardcodes the Python binary path (and the same python binary points to different versions on different systems), I had to go to `.git/hooks/pre-commit` and modify the following line to:
```
INSTALL_PYTHON=`which python3`
```

This won't be an issue on most systems, it's just an unfortunate combination of two issues:
1. The same exact path points to two versions, and 
2. Python 3.7 doesn't install `pre-commit` properly because of an issue installing the latest version of PyYAML

2023-03-16 23:23 UTC, bvanessen commented on CONTRIBUTING.md
> +Make sure you have `clang-format` installed for C/C++ formatting and `yapf` for Python formatting.
```suggestion
Make sure you have `clang-format` installed for C/C++ formatting and `yapf` for Python formatting.
Note that once `pre-commit` is installed in the `.git/hooks` directory of a repository, you will need to execute
all of your `git` commands from a system with a `python` that has `pre-commit` installed.
```

2023-03-16 23:24 UTC, bvanessen approved these changes

2023-03-16 23:28 UTC, bvanessen commented on CONTRIBUTING.md
> +but allow some exceptions to create layers in the LBANN Python frontend.
```suggestion
but allow some exceptions to create layers in the LBANN Python frontend.

## Troubleshooting

When working on systems with older `python@3.7.2` there is a trick to getting pre-commit installed via `pip`:
`python3 -m pip install --user pyyaml==5.1`
`python3 -m pip install --user pre-commit`
```

2023-03-17 00:29 UTC, tbennun commented
@bvanessen should work much smoother now

2023-03-17 05:20 UTC, bvanessen approved these changes

2023-03-17 05:20 UTC, bvanessen commented on scripts/pre-commit-hook.sh
> +CLANG_FORMAT="${CLANG_FORMAT:-clang-format}"
```suggestion
CLANG_FORMAT="${CLANG_FORMAT:-$(which clang-format)}"
```

2023-03-17 05:20 UTC, bvanessen commented on scripts/pre-commit-hook.sh
> +    echo "clang-format not found. Either install it or set the CLANG_FORMAT environment variable to its path"
```suggestion
    echo "clang-format not found (CLANG_FORMAT=${CLANG_FORMAT}). Either install it or set the CLANG_FORMAT environment variable to its path"
```

2023-03-17 05:27 UTC, merged