Added documentation for operator layers
LLNL/lbann pull request #2211
Opened 2023-03-02 00:13 UTC by graham63

2023-03-02 23:46 UTC, benson31 requested changes
Overall this is good, just a few suggestions so it doesn't look like
they're in-place operators (they aren't).

2023-03-02 23:46 UTC, benson31 commented on docs/operators.rst
> +   x = (c - x)
```suggestion
   y = (c - x)
```

2023-03-02 23:46 UTC, benson31 commented on docs/operators.rst
> +   x = c * x
```suggestion
   y = c * x
```

2023-03-02 23:46 UTC, benson31 commented on docs/operators.rst
> +   x = (x - c)
```suggestion
   y = (x - c)
```

2023-03-02 23:48 UTC, benson31 reviewed
Also, do we want to maybe put the Python Front-End names for these in
there? (For both the operator and the OperaorLayer shortcut?)

2023-03-24 21:21 UTC, bvanessen approved these changes

2023-03-24 21:22 UTC, merged